### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by cloke** [MaxKramer/SwiftLuhn#1]
The current version does not work under Swift 3.

**Comment by MaxKramer** [comment]
Hi @cloke, sorry for the late reply, I only just saw this.

I've just pushed some changes up to the swift_3 branch. Tests are failing as it seems that Circle doesn't support Xcode 8 yet.

Max.

**Comment by MaxKramer** [comment]
@cloke if you could take a look at #2 that would be great!

**Comment by piv199** [comment]
@MaxKramer make master of kind swift3, and current master of kind swift 2.2

**Comment by MaxKramer** [comment]
@piv199 all done :)
