### ISSUE TITLE
update latest changes to pod

### ISSUE THREAD

**Issue by Alexookah** [maxkramer/SwiftLuhn#12]
I used pod 'SwiftLuhn' and it doesn't include your latest changes for swift 4.

**Comment by hx0a1q** [comment]
I'm using Carthage, and it says: "Incompatible Swift version"

**Comment by maxkramer** [comment]
Hi both, sorry for the late reply. As you can probably tell, I haven't had much time to maintain the project as of recent.

@Alexookah I've pushed an updated version of the Podfile, so it should now be working. Can you confirm?

@hx0a1q I've created a new tag (0.2.2) with the Swift 4 framework, as well as the dYSM, please can you confirm it's working?

See https://github.com/maxkramer/SwiftLuhn/releases/tag/0.2.2 for more info.

Best,
Max.
