### ISSUE TITLE
`stringValue()` for dinerClub card returns "Diner\'s Club" instead "Diner's Club"

### ISSUE THREAD

**Issue by dhvlshah88** [maxkramer/SwiftLuhn#13]
The issue is as explained above, `Diner's Club` needs to have escaped character '\' to return a normal string literal.

**Comment by maxkramer** [comment]
@dhvlshah88 thanks for the issue, sorry it's taken this long to get to it. As you can see in the test, I can't replicate this issue. Do you have any additional information?
