### ISSUE TITLE
Invalid error

### ISSUE THREAD

**Issue by wixvii** [maxkramer/SwiftLuhn#17]
### What did you do?

When I check my mastercard debit card it gives me invalid error

Please replace this with what you did.

### What did you expect to happen?

Please replace this with what you expected to happen.

### What actually happened instead?

Please replace this with what happened instead.

### Environment

List the software versions you're using:

 - Xcode Version: *?.? (????)* (Open Xcode; In menubar: Xcode > About Xcode)
 - Swift Version: *?.?* (Open Xcode Preferences; Components > Toolchains. If none, use `Xcode Default`.)

Please also mention which package manager you used and its version. Delete the
other package managers in this list:

 - Cocoapods: *?.?.?* (Use `pod --version` in Terminal)
 - Carthage: *?.?* (Use `carthage version` in Terminal)
 - Swift Package Manager *?.?.? (swiftpm-???)* (Use `swift build --version` in Terminal)

**Comment by maxkramer** [comment]
@wixvii I'm going to need more information than it simply doesn't work in order to look into this.
