### ISSUE TITLE
Release version 0.2 on Cocoapods

### ISSUE THREAD

**Issue by leobarrospereira** [MaxKramer/SwiftLuhn#3]
Hi,

On https://cocoapods.org the version available is 0.1 that is not compatible with Swift 3.

Will you release the new version on cocoapods?

At this moment I'm using the library pointing directly to your tag 0.2 on github.

Thanks!

**Comment by MaxKramer** [comment]
Done! 

I manually updated the podspec in the past when I did the migration, but it looks like I didn't push it to the trunk.

**Comment by leobarrospereira** [comment]
Thanks!
