### ISSUE TITLE
0.1.1 Tag not working

### ISSUE THREAD

**Issue by RodolfoAntonici** [MaxKramer/SwiftLuhn#4]
Hello there,

For some reason I have this error on pod install

> [!] Unable to satisfy the following requirements:
> 
> - `SwiftLuhn (~> 0.1.1)` required by `Podfile`
> 
> None of your spec sources contain a spec satisfying the dependency: `SwiftLuhn (~> 0.1.1)`.

and in the pod file I have this:

    pod 'SwiftLuhn', '~> 0.1.1'

What is happening? Broken tag?

**Comment by MaxKramer** [comment]
You're right - the tag for 0.1.1 doesn't exist in pod trunk for some reason.

See: `pod search swiftluhn`.

The 0.1.0 tag will provide the same functionality for Swift 2.X, please use that instead.

Otherwise you can specify the commit instead of the tag in your podfile.
